import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/hero'
import Navbar from '../components/navbar'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Celsius E Aray</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Grechen+Fuemen&display=swap" rel="stylesheet" />
        <link rel="icon" href="/celsiusDevLogoRedondo.svg" />
      </Head>
      <main>
        <Navbar />
        <Hero />
      </main>
    </>
  )
}

export default Home
